config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

	# Authentication
	# @implemented
  devise_for :users, {
  	# some code here
  }

  # Application
  # @implemented
  root to: 'home#index'

  # Searchs
  # @implemented
  get '/buscar' => 'jobs#search', as: :search_jobs

  # Jobs
  # @implemented
  resources :users
  resources :job_applications, only: [:create]
  resources :jobs do

   	# Member
   	# @implemented
   	member do
   		post 'active'   => 'jobs#active'
   		post 'inactive' => 'jobs#inactive'
   	end

   	# Collection
   	# @implemented
   	collection do
   		get 'my-jobs' => 'jobs#my_jobs'
   	end
  end

  # Profile
  # @implemented
  resources :profiles, only: [:show, :edit, :update, :edit, :destroy]

  # Dashboard
  # @implemented
  namespace :dashboard, constraint: { subdomain: 'dashboard' } do
    get '/' => 'home#index'
    get '/jobs' => 'jobs#index'
    get '/invoices' => 'invoices#index'
  end
end

app/models/profile.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: profiles
#
#  id               :integer          not null, primary key
#  about            :text
#  logo             :string
#  name             :string
#  phone            :string
#  responsible_name :string
#  slug             :string
#  website          :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  city_id          :integer
#  user_id          :integer
#
# Indexes
#
#  index_profiles_on_city_id  (city_id)
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  include ProfileFilter

  extend FriendlyId
  friendly_id :name, use: [:slugged]

  self.table_name  = 'profiles'
  self.primary_key = 'id'

  # Attachment
  # @implemented
  has_one_attached :logo
  belongs_to :city

  # Relationship
  # @implemented
  belongs_to :user
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController <:: ApplicationController
	before_action :authenticate_user!
	before_action :set_profile, only: [:edit, :update]
	rescue_from ActiveRecord::RecordNotFound, with: :not_found
	respond_to :html, :json, :js

	def show
		@profile = Profile.friendly.find(params[:id])
		redirect_to user_path(@profile.user)
	end

	def edit
		respond_with @profile
	end

	def update
		@profile.update(profile_params)
		flash[:notice] = 'Perfil atualizado com sucesso.'
		redirect_to user_path(@profile.user)
	end

	def destroy
		current_user.destroy
		flash[:notice] = 'Perfil removido com sucesso.'
		redirect_to root_path
	end

	private

	def set_profile
		@profile = current_user.profile
	end

	def profile_params
		params.require(:profile)
			.permit(:logo, :name, :phone, :about, :website, :responsible_name, :city_id)
	end
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
	<%= has_errors?(profile) %>

	<div class="field padding">
		<%= f.label :logo, 'Logo' %>
		<%= f.file_field :logo %>
	</div>

	<div class="field padding">
		<%= f.label :name, 'Nome da Empresa' %>
		<%= f.text_field :name, class: 'form-control',
		required: 'required', placeholder: 'Digite o nome' %>
	</div>

	<div class="field padding">
		<%= f.label :phone, 'Telefone' %>
		<%= f.text_field :phone, class: 'form-control',
		required: 'required', placeholder: 'Digite o telefone' %>
	</div>

	<div class="field padding">
		<%= f.label :about, 'Descrição' %>
		<%= f.text_area :about, class: 'form-control', required: 'required',
		placeholder: 'Digite a descrição', autocomplete: 'off' %>
	</div>

	<div class="field padding">
		<%= f.label :responsible_name, 'Nome do Responsavel' %>
		<%= f.text_field :responsible_name, class: 'form-control',
		required: 'required', placeholder: 'Digite o nome do Responsavel' %>
	</div>

	<div class="field padding">
		<%= f.label :website, 'Website' %>
		<%= f.url_field :website, class: 'form-control', required: 'required',
		placeholder: 'Digite o website', autocomplete: 'off' %>
	</div>

	<div class="field padding">
		<%= f.label :city_id, 'Cidade' %>
		<%= f.collection_select(:city_id, City.all, :id, :name,
		{ prompt: 'Selecionar Cidade' }, { class: 'form-control', required: 'required' }) %>
	</div>

	<div class="acttions padding text-center"><br>
		<%= f.submit nil, class: 'btn btn-primary btn-lg top' %>
	</div>
<% end %>

app/views/profiles/edit.html.erb
<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class='col-md-6 col-md-offset-3'>
          <div class='panel panel-default'>
            <div class='panel-body'>
              <%= render 'form', profile: @profile %>
            </div>
          </div>
        </div>
			</div>
		</div>
	</div>
</section>

app/views/profiles/show.html.erb
<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class="field">
					<div class='panel panel-default'>
						<div class='panel-default'>
							<div class='panel-body'>
							<h5 class='bold'>Logo</h5>
								<p>Docker</p>
							</div>
						</div>
					</div>
				</div>

				<div class="field">
					<div class='panel panel-default'>
						<div class='panel-body'>
							<h5 class='bold'>Nome da Empresa</h5>
							<%= @profile.name %>
						</div>
					</div>
				</div>

				<div class="field">
					<div class='panel panel-default'>
						<div class='panel-body'>
							<h5 class='bold'>Telefone</h5>
							<%= @profile.phone %>
						</div>
					</div>
				</div>

				<div class="field">
					<div class='panel-default'>
						<div class='panel-body'>
							<h5 class='bold'>Descrição</h5>
							<p><%= @profile.website %></p>
						</div>
					</div>
				</div>

				<div class="field">
					<div class='panel-default'>
						<div class='panel-body'>
							<h5 class='bold'>Website</h5>
							<%= @profile.responsible_name %>
						</div>
					</div>
				</div>

				<div class="field">
					<div class='panel panel-default'>
						<div class='panel-body'>
							<h5 class='bold'>Nome do Responsavel</h5>
							<%= @profile.responsible_name %>
						</div>
					</div>
				</div>

				<div class="field">
					<div class='panel panel-default'>
						<div class='panel-body'>
							<h5 class='bold'>Cidade</h5>
							<%= @profile.city.name %>
						</div>
					</div>
				</div>

				<div class="actions">
					<%= link_to 'Editar', edit_profile_path(current_user.profile) %>
					<%= link_to 'Voltar', jobs_path %>
				</div>

				<div class="delete-profile">
					<% if current_user.eql?(@profile.user) %>
						<%= link_to profile_path(current_user.profile),
							method: :delete,
							data: { confirm: 'Você realmente deseja excluir seu perfil?' },
							class: 'btn btn-danger btn-lg top' do  %>
								Deletar Conta
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>