config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

	# Authentication
	# @implemented
  devise_for :users, {
  	# some code here
  }

  # Application
  # @implemented
  root to: 'home#index'

  # Searchs
  # @implemented
  get '/buscar' => 'jobs#search', as: :search_jobs

  # Jobs
  # @implemented
  resources :users
  resources :job_applications, only: [:create]
  resources :jobs do

   	# Member
   	# @implemented
   	member do
   		post 'active'   => 'jobs#active'
   		post 'inactive' => 'jobs#inactive'
   	end

   	# Collection
   	# @implemented
   	collection do
   		get 'my-jobs' => 'jobs#my_jobs'
   	end
  end

  # Profile
  # @implemented
  resources :profiles, only: [:show, :edit, :update, :edit, :destroy]

  # Dashboard
  # @implemented
  namespace :dashboard, constraint: { subdomain: 'dashboard' } do
    get '/' => 'home#index'
    get '/jobs' => 'jobs#index'
    get '/invoices' => 'invoices#index'
  end
end

app/models/job.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: jobs
#
#  id                 :integer          not null, primary key
#  apply_content      :string
#  description        :text
#  expiration         :date
#  featured           :boolean
#  how_to_apply       :integer
#  location           :string
#  modality           :integer
#  salary             :float
#  slug               :string
#  status             :integer
#  title              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  city_id            :integer
#  deficiency_id      :integer
#  hiring_type_id     :integer
#  occupation_area_id :integer
#  user_id            :integer
#
# Indexes
#
#  index_jobs_on_city_id             (city_id)
#  index_jobs_on_deficiency_id       (deficiency_id)
#  index_jobs_on_hiring_type_id      (hiring_type_id)
#  index_jobs_on_occupation_area_id  (occupation_area_id)
#  index_jobs_on_user_id             (user_id)
#
class Job < ApplicationRecord
  include JobFilter
  include Mailerable

  extend FriendlyId
  friendly_id :title, use: [:slugged]

	self.table_name  = 'jobs'
	self.primary_key = 'id'

	# Relationships
	# @implemented
  belongs_to :deficiency, optional: true
	belongs_to :occupation_area
	belongs_to :hiring_type
	belongs_to :user

	# Enum
	# @implemented
	enum status: ['active', 'expired']
	enum modality: ['Office', 'Remote']
	enum how_to_apply: ['Email', 'URL']

	# Scope
	# @implemented
	scope :featured, -> { where(featured: true) }
	scope :by_title, -> (title) { where("title LIKE ?", "%#{title}%") }
	scope :recents,  -> { where(created_at: :desc) }
	scope :lasts,    -> { where(created_at: :asc) }
	scope :active,   -> { where(status: 'active') }
	scope :expired,  -> { where(status: 'expired') }

	# Callbacks
	# @implemented
	after_create :set_expiration_date

	# Validations
	# @implemented
	validates_uniqueness_of :title, scope: [:user_id]

	validates  :title,
					 	 presence: true,
						 allow_blank: false,
						 length: { minimum: 3, maximum: 45 }

  # Methods
  # @implemented
  def set_expiration_date
  	self.expiration = Date.today + 15.day
  	self.status = 'active'
  	save
  end

  def expire
  	self.status = 'expired'
  	save
  end
end

app/controllers/dashboard/jobs_controller.rb
# frozen_string_literal: true

module Dashboard
	class JobsController <:: HomeController

		def index
		end
	end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController <:: ApplicationController
	before_action :set_job, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :not_found
	respond_to :html, :json, :js

	def index
		@jobs = Job.filter(filtering_params).page(params[:page]).per(1)
		respond_with @jobs
	end

	def new
		@job = Job.new
		respond_with @job
	end

	def show
		respond_with @job
	end

	def create
		@job = current_user.jobs.create(job_params)
		respond_with @job
	end

	def edit
		respond_with @job
	end

	def update
		@job.update(job_params)
		respond_with @job
	end

	def destroy
		@job.destroy
		respond_with @job
	end

	def search
		@jobs = Job.active.by_title(params[:search][:q])
		respond_with @jobs
	end

	def active
		@job = Job.find(params[:id])
		@job.update(status: 'active')
		flash[:notice] = 'Vaga ativada com sucesso.'
		redirect_to job_path(@job)
	end

	def inactive
		@job = Job.find(params[:id])
		@job.update(status: 'expired')
		flash[:notice] = 'Vaga expirada com sucesso.'
		redirect_to job_path(@job)
	end

	def my_jobs
		@jobs = current_user.jobs.active
		respond_with @jobs
	end

	private

	def set_job
		@job = Job.friendly.find(params[:id])
	end

	def filtering_params
		params[:search].slice(:keywords, :location) if (params)
	end

	def job_params
		params.require(:job).permit(:title, :description, :occupation_area_id,
						 :hiring_type_id, :salary, :featured, :modality, :location,
						 :how_to_apply, :apply_content, :deficiency_id, :city_id,
						 :user_id)
	end
end

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
	<%= has_errors?(job) %>

	<div class="field col-md-12">
		<%= f.label :title, 'Titulo' %> <br />
		<%= f.text_field :title, class: 'form-control', required: 'required',
		placeholder: 'Titulo da Vaga' %>
	</div>

	<div class="field col-md-12">
		<%= f.label :description, 'Descrição' %> <br />
		<%= f.text_area :description, class: 'form-control', required: 'required',
		placeholder: 'Descrição da Vaga', autocomplete: 'off' %>
	</div>

	<div class="field col-md-6">
		<%= f.label :occupation_area_id, 'Área de Ocupação' %>
		<%= f.collection_select(:occupation_area_id, OccupationArea.all, :id, :name,
		{ prompt: 'Selecionar Área de Ocupação' }, { class: 'form-control', required: 'required'}) %>
	</div>

	<div class="field col-md-6">
		<%= f.label :hiring_type_id, 'Tipo de Contratação' %>
		<%= f.collection_select(:hiring_type_id, HiringType.all, :id, :name,
		{ prompt: 'Selecionar Tipo de Contratação' }, { class: 'form-control', required: 'required'}) %>
	</div>

	<div class="field col-md-12">
		<%= f.label :deficiency_id, 'Deficiencia' %><br>
		<small>Preencha apenas se a vaga for direcionada para deficientes.</small>
		<%= f.collection_select(:deficiency_id, Deficiency.order(:name), :id, :name,
		{ prompt: 'Selecionar Deficiência' }, { class: 'form-control', required: 'required '}) %>
	</div>

	<div class="field col-md-12">
		<%= f.label :salary, 'Salário' %>
		<%= f.number_field :salary, class: 'form-control', required: 'required',
		placeholder: 'Digite o Salário', autocomplete: 'off' %>
	</div>

	<div class="field col-md-12">
		<div class="field">
			<%= f.label :modality, 'Localização' %>
			<%= f.radio_button :modality, 'Office' %> Presencial
			<%= f.radio_button :modality, 'Remote' %> Remoto
		</div>

		<%= f.text_field :location, class: 'form-control',
		required: 'required', placeholder: 'Digite a Localização',
		autocomplete: 'off' %>
	</div>

	<div class="field col-md-12">
		<div class="field">
			<%= f.label :how_to_apply, 'Como se candidatar' %>
			<%= f.radio_button :how_to_apply, 'Email' %> Email
			<%= f.radio_button :how_to_apply, 'URL' %> URL
		</div>

		<%= f.text_field :apply_content, class: 'form-control',
		required: 'required', placeholder: 'Digite a URL/E-mail',
		autocomplete: 'off' %>
	</div>

	<div class="field col-md-12">
		<%= f.label :city_id, 'Cidade' %>
		<%= f.collection_select(:city_id, City.all, :id, :name,
		{ prompt: 'Selecionar Cidade' }, { class: 'form-control', required: 'required' }) %>
	</div>

	<div class="actions col-md-12"> <br>
		<div class='text-center'>
			<%= f.submit nil, class: 'btn btn-primary btn-lg top' %>
		</div>
	</div>
<% end %>

app/views/jobs/_job.html.erb
<div class="job">
	<div class='panel panel-default'>
		<div class='panel-body'>
			<div class='col-md-2'>
				<div class="jumbotron" style='height: 125px;'></div>
			</div>

			<div class='col-md-8'>
				<h4 class='bold'><%= link_to job.title, job_path(job) %></h4>

				<%= link_to '', class: 'pull-right',
					style: 'top: 0px; margin-top: -40px; font-size: 22px;' do %>
					<i class="far fa-bookmark"></i>
				<% end %>

				<ul class="list-unstyled list-inline">
					<li class='bold'>
						<i class="fas fa-briefcase"></i>
						<%= job.user.profile.name %>
					</li>
					<li class='bold'>
						<i class="fas fa-map-marker-alt"></i>
						<%= job.modality %>
						<span>(<%= job.location %>)</span>
					</li>
				</ul>
				<p><%= truncate(job.description, length: 156) %></p>
			</div>

			<div class="col-md-2">
				<ul class="list-unstyled">
					<li>
						<%= job.created_at.strftime("%M/%Y") %>
					</li>
					<li>
						<span class='badge'>
							<%= job.modality %>
						</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/jobs/_job_application.html.erb
<div class='col-md-10 col-md-offset-1'>
<%= form_for(job_application, { multipart: true }) do |f| %>
	<%= has_errors?(job_application) %>

	<div class="field padding">
		<%= f.label :name, 'Seu nome' %>
		<%= f.text_field :name, class: 'form-control', required: 'required',
		placeholder: 'Digite o nome', autocomplete: 'off' %>
	</div>

	<div class="field padding">
		<%= f.label :email, 'Seu email' %>
		<%= f.text_field :email, class: 'form-control', required: 'required',
		placeholder: 'Digite o e-mail', autocomplete: 'off' %>
	</div>

	<div class="field padding">
		<%= f.label :salary, 'Pretensão salarial' %>
		<%= f.number_field :salary, class: 'form-control', required: 'required',
		placeholder: 'Digite o salário', autocomplete: 'off' %>
	</div>

	<div class="field padding">
		<%= f.label :cv_field, "Selecione seu currículo" %>
		<%= f.file_field :cv_field %>
	</div>

	<div class="field padding">
		<%= f.label :short_letter, 'Carta de Apresentação' %>
		<%= f.text_area :short_letter, class: 'form-control', required: 'required',
		placeholder: 'Digite sua bio', autocomplete: 'off' %>
	</div>

	<div class="action text-center"> <br />
		<%= f.submit 'Enviar candidatura', class: 'btn btn-primary btn-lg top' %>
	</div>
<% end %>
</div>

app/views/jobs/edit.html.erb
<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class='col-md-8 col-md-offset-2'>
					<div class="panel panel-default">
						<div class="panel-body">
							<%= render 'form', job: @job %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/jobs/index.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id="presenter" class='jumbotron' style='margin-top: -20px;'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class='col-md-12 text-center'>
					<%= image_tag('logo.png', class: 'logo') %>
				</div>

				<div class="col-md-8 col-md-offset-2">
					<%= form_for(:search, { url: jobs_path, method: :get }) do |f| %>

					<div class='panel panel-default'>
						<div class='panel-body'>
					  	<div class="col-md-5">
					    	<%= f.text_field :keywords, class: 'form-control',
					    	autocomplete: 'off', placeholder: 'Palavras-chave' %>
					  	</div>

					  	<div class='col-md-5'>
				       	<%= f.text_field :location, class: 'form-control',
				       	autocomplete: 'off', placeholder: 'Local' %>
				    	</div>

					  	<div class="col-md-2 text-center">
						   	<%= f.submit 'Buscar', class: 'btn btn-primary btn-lg' %>
					  	</div>
					  </div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class='row'>
					<div class='col-md-3'>
						<div class="row">
							<div class="col-md-12">
								<div class="panel panel-default">
									<div class="panel-body">
										<h4 class='bold'>
										<i class="fas fa-caret-right"></i>
										Refinar por Cidade</h4>
									  <ul class='list-unstyled'>
									  	<% City.all.each do |city| %>
									  	<li>
									  		<%= city.name %>
									  		<%= link_to jobs_path(city: city) do %>
									  			<span class='bold'>(<%= city.jobs.count %>)</span>
									  		<% end %>
									  	</li>
									  	<% end %>
									  </ul>
									</div>
								</div>
							</div>

							<div class="col-md-12">
								<div class='panel panel-default'>
									<div class='panel-body'>
										<h4 class='bold'>
										<i class="fas fa-caret-right"></i>
										Refinar por Áreas de atuação</h4>
									  <ul class='list-unstyled'>
									  	<% OccupationArea.all.each do |area| %>
									  	<li>
									  		<%= area.name %>

									  		<%= link_to jobs_path(occupation_area: area) do %>
									  		<span class='bold'>
									  			(<%= area.jobs.count %>)
									  		</span>
									  		<% end %>
									  	</li>
									  	<% end %>
									  </ul>
									</div>
								</div>
							</div>

							<div class="col-md-12">
								<div class='panel panel-default'>
									<div class='panel-body'>
										<h4 class='bold'>
										<i class="fas fa-caret-right"></i>
										Refinar por tipo de contratação</h4>
										<ul class='list-unstyled'>
											<% HiringType.all.each do |type| %>
											<li>
												<%= type.name %>

												<%= link_to jobs_path(hiring_type: type) do %>
												<span class='bold'>
													(<%= type.jobs.count %>)
												</span>
												<% end %>
											</li>
											<% end %>
										</ul>
									</div>
								</div>
							</div>

							<div class="col-md-12">
								<div class="panel panel-default">
									<div class="panel-body">
										<i class="fas fa-caret-right"></i>
										Refinar por vagas especiais</h4>

										<ul class='list-unstyled'>
											<% Deficiency.all.each do |deficiency| %>
											<li>
												<%= deficiency.name %>

												<%= link_to jobs_path(deficiency: deficiency) do %>
												<span class='bold'>
													(<%= deficiency.jobs.count %>)
												</span>
												<% end %>
											</li>
											<% end %>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class='col-md-9'>

						<% if current_user %>
						<div class='row'>
							<div class='col-md-12'>
								<div class='panel panel-default'>
									<div class='panel-body text-right'>
										<%= link_to 'Adicionar Vaga',
										new_job_path, class: 'btn btn-primary btn-lg top' %>
									</div>
								</div>
							</div>
						</div>
						<% end %>

<!-- 						<div id="search"><br>
							<%= form_for(:search, { url: search_jobs_path, method: :get }) do |f| %>
								<div class="field">
									<%= f.text_field :q, placeholder: 'Buscar...', class: 'form-control' %>
								</div>
							<% end %>
						</div>
						<br> -->

					  <div id='jobs'>
					  	<% @jobs.each do |job| %>
					  		<%= render job %>
					  	<% end %>
						</div>

						<div id='pagination'>
							<div class='text-center'>
								<%= paginate(@jobs) %>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/jobs/my_jobs.html.erb
<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				
			</div>
		</div>
	</div>
</section>

app/views/jobs/new.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
        <div class='col-md-8 col-md-offset-2'>
          <div class="panel-heading">
            <%= link_to jobs_path,
              class: 'btn btn-primary btn-lg top' do %>
                <i class="fas fa-chevron-circle-left"></i>
                Voltar
            <% end %>
          </div>

          <div class='panel panel-default'>
            <div class='panel-body'>
              <%= render 'form', job: @job %>
            </div>
          </div>
        </div>
			</div>
		</div>
	</div>
</section>

app/views/jobs/search.html.erb
<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<%= link_to 'Adicionar Vaga', new_job_path %>

				<div id="search">
					<%= form_for(:search, { url: search_jobs_path, method: :get }) do |f| %>
						<div class="field">
							<%= f.text_field :q, placeholder: 'Titulo' %>
						</div>
					<% end %>
				</div>
			  
			  <% @jobs.each do |job| %>
          <div class="job">
          	<h4><%= link_to job.title, job_path(job) %></h4>
          	<p><%= job.description %></p>
          </div>
			  <% end %>

			 <% if @jobs.empty? %>
			 	<p>Nenhuma vaga encontrada.</p>
			 <% end %>
			</div>
		</div>
	</div>
</section>

app/views/jobs/show.html.erb
<section id="presenter" style="padding-bottom: 80px;
padding-top: 40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-12">
            <%= link_to users_path, class: 'btn btn-primary btn-lg top',
              style: 'padding: 13px;' do %>
              <i class="fas fa-arrow-circle-left"></i>
              Voltar
            <% end %>

            <% if (current_user && owner?(@job))  %>
              <%= link_to edit_profile_path(current_user.profile),
                class: 'btn btn-default btn-lg top',
                style: 'background-color: transparent;
                color: #FFF; padding: 13px;
                font-weight: bold;
                border: 2px solid #EEE;' do %>
                  Editar Vaga
              <% end %>
            <% end %>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="col-md-12">
             <h1 class='bold'><%= @job.title %></h1>
             <ul class="list-unstyled list-inline">
                <li>
                  <i class="fas fa-map-marker-alt"></i>
                  <%= @job.user.profile.name %>,
                </li>
                <li>
                  <i class="fas fa-globe-americas bold"></i>
                  <%= @job.modality %>
                  ( São Borja, Rio Grande do Sul, Brasil)
                </li>
                <li>
                	<i class="fas ga-globe-americas bold"></i>
                	<%= @job.created_at %>
                </li>
              </ul>
              <br>

              <ul class="list-unstyled list-inline">
              	<li>
              		<span class='badge'>
              			<%= @job.hiring_type.name %>
              		</span>
              	</li>
              	<li>
              		<span class='badge'>
              			<%= @job.occupation_area.name %>
              		</span>
              	</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="list-unstyled">

<!-- 					<% if (@job.active?) then %>
						<li>
							<%= link_to 'Expirar', inactive_job_path(@job), method: :post,
							class: 'btn btn-primary btn-lg' %>
						</li>
					<% else %>
						<li>
							<%= link_to 'Ativar', active_job_path(@job), method: :post,
							class: 'btn btn-primary btn-lg' %>
						</li>
					<% end %>
				</ul> -->

				<div class='row'>
					<div class='col-md-8'>
  			    <div class="field"><br>
              <h2 class='bold uppercase'>Descrição da Vaga</h2>
              <br>
  			    	<p><%= @job.description %></p>
  			    </div>

            <div class="field">
              <h2 class='bold uppercase'>Salário</h2>
              <p><%= @job.salary %></p>
            </div>

  			    <div id="application">
  			    	<% if (@job.how_to_apply.eql?('Email')) then %>

  			    		<button type="button" class="btn btn-primary btn-lg"
  			    			data-toggle="modal" data-target="#jobApplicationModal">
  	  							Quero me candidatar
  							</button>


<!--   			    		<div class="modal fade" id="jobApplicationModal" tabindex="-1"
  			    		role="dialog" aria-labelledby="myModalLabel">
  							  <div class="modal-dialog" role="document">
  							    <div class="modal-content">
  							      <div class="modal-header">
  							        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  							        <h4 class="modal-title text-center bold" id="myModalLabel">
  							        	Candidate-se a vaga de <%= @job.title %>
  							        </h4>
  							      </div>
  							      <div class="modal-body">
  							        <%= render 'job_application', job_application: JobApplication.new %>
  							      </div>
  							      <div class="modal-footer">
  							      </div>
  							    </div>
  							  </div>
  							</div> -->

    			    	<% else %>
                  <div class='col-md-12'>
                    <div class='panel panel-default'>
    			    		     <div class='panel-body'>
                         <%=  link_to @job.apply_content,
        			    			  class: 'btn btn-primary btn-lg top' do %>
        			    				 Quero me Candidata
        			    		   <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
    			    	<% end %>
              </div>
            </div>

            <div class="col-md-4" style='margin-top: -60px;'>
              <div class="panel panel-default">
                <div class="panel-body">
                  <div class='text-center'>
                    <%= image_tag(@job.user.profile.logo,
                      style: 'width: 120px; height: 120px;') %>
                  </div>
                  <h3 class='text-center bold'>
                    Sobre a <%= @job.user.profile.name %>
                  </h3>
                  <p><%= truncate(@job.user.profile.about, length: 145) %></p>

                  <div class='text-center'>
                    <%= link_to user_path(@job.user.profile),
                      class: 'btn btn-primary btn-lg top' do %>
                        Perfil da Empresa
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
			</div>
		</div>
	</div>
</section>