config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

	# Authentication
	# @implemented
  devise_for :users, {
  	# some code here
  }

  # Application
  # @implemented
  root to: 'home#index'

  # Searchs
  # @implemented
  get '/buscar' => 'jobs#search', as: :search_jobs

  # Jobs
  # @implemented
  resources :users
  resources :job_applications, only: [:create]
  resources :jobs do

   	# Member
   	# @implemented
   	member do
   		post 'active'   => 'jobs#active'
   		post 'inactive' => 'jobs#inactive'
   	end

   	# Collection
   	# @implemented
   	collection do
   		get 'my-jobs' => 'jobs#my_jobs'
   	end
  end

  # Profile
  # @implemented
  resources :profiles, only: [:show, :edit, :update, :edit, :destroy]

  # Dashboard
  # @implemented
  namespace :dashboard, constraint: { subdomain: 'dashboard' } do
    get '/' => 'home#index'
    get '/jobs' => 'jobs#index'
    get '/invoices' => 'invoices#index'
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				
				<div class="col-md-3">
					<h4 class="bold">Sitemap</h4>
					<ul class="list-unstyled">
						<li><%= link_to 'Home', root_path %></li>
						<li><%= link_to 'Contato', root_path %></li>
						<li><%= link_to 'Sobre Nós', root_path %></li>
						<li><%= link_to 'Termos de Uso', root_path %></li>
					</ul>
				</div>

				<div class="col-md-3">
					<h4 class='bold'>Empresas</h4>
					<ul class="list-unstyled">
						<li><%= link_to 'Publicar Vagas', new_job_path %></li>
						<li><%= link_to 'Entrar', new_user_session_path %></li>
					</ul>
					<br>

					<h4 class='bold'>Redes Sociais</h4>
					<ul class="list-unstyled list-inline">
						<li>
							<%= link_to 'https://facebook.com/portalfronteirico',
								target: '_blank' do %>
								<i class="fab fa-facebook-square"></i>
							<% end %>
						</li>
						<li>
							<%= link_to 'https://instagram.com/portalfronteirico',
								target: '_blank' do %>
								<i class="fab fa-instagram"></i>
							<% end %>
						</li>
						<li>
							<%= link_to 'https://instagram.com/pfronteirico',
								target: '_blank' do %>
								<i class="fab fa-twitter"></i>
							<% end %>
						</li>
							<%= link_to 'https://linkein.com/in/portalfronteirico',
								target: '_blank' do %>
								<i class="fab fa-linkedin"></i>
							<% end %>
						</li>
					</ul>
				</div>

				<div class="col-md-3">
					<h4 class='bold'>Candidatos</h4>
					<ul class="list-unstyled">
						<li><%= link_to 'Buscar Vagas', jobs_path %></li>
					</ul>
					<br>

					<h4 class='bold'>Curta no Facebook</h4>
					<div id='facebook-iframe'>
						<%= render 'shared/facebook-iframepage' %>
					</div>
				</div>

				<div class="col-md-3">
					<h4 class='bold'>Procurando Estágio/Estágiarios?</h4>
					<ul class="list-unstyled">
						<li><%= link_to 'Buscar Vagas', jobs_path %></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div id='copyright'>
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h5>Portal Fronteiriço - &copy <%= Date.today.year %></h5>
					<ul class="list-unstyled list-inline">
						<li><%= link_to 'Termos de Privacidade', '' %></li>
						<li><%= link_to 'Noticias', 'https://portalfronteirico.com' %></li>
					</ul>
				</div>

				<div class="col-md-6 text-right">
					<h5 class='bold'>Proudly hosted by Heroku</h5>
					<p>Todos os direitos reservados.</p>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
	<nav class="navbar navbar-default">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
      data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
      aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    	<%= link_to root_path, class: 'navbar-brand' do %>
    		Vagas
    	<% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><%= link_to 'Vagas', jobs_path %></li>
      	<li><%= link_to 'Empresas', users_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if (current_user) then %>
        	<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        	<li><%= link_to 'Minha Conta', dashboard_path %></li>
        <% else %>
        	<li><%= link_to 'Entrar', new_user_session_path %></li>
        	<li><%= link_to 'Criar conta', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html/
<html lang="pt-BR">
  <head>
    <title>Portal Fronteiriço | <%= yield :title %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css"><%= yield :css %></style>
    <script type="text/javascript"><%= yield :js %></script>
    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
    <script type="application/ld+json"><%= yield :ld_json %></script>
  </head>
  <body class="<%= controller.controller_name %>">
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>

    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v9.0&appId=557006248313894&autoLogAppEvents=1" nonce="NeOchGwo"></script>

    <!-- addons -->
    <%= render 'shared/freshchat' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Portal Fronteiriço | <%= yield :title %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css"><%= yield :css %></style>
    <script type="text/javascript"><%= yield :js %></script>
    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
    <script type="application/ld+json"><%= yield :ld_json %></script>
  </head>
  <body class="<%= controller.controller_name %>">
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class='text-center'>
            <%= image_tag('logo.png',
              style: 'width: 120px; height: 120px;
              border-radius: 120px; margin-top: 10px;') %>
          </div>
          <h1 class='text-center bold'>MINHA CONTA</h1>
          <hr>

          <div class='col-md-6 col-md-offset-3'>
            <nav id='navigation'>
              <ul class="nav nav-pills">
                <li><%= link_to 'Dashboard', dashboard_path %></li>
                <li><%= link_to 'Vagas Publicadas', jobs_path %></li>
                <li><%= link_to 'Invoices', dashboard_path %></li>
                <li><%= link_to 'Perfil da Empresa', edit_profile_path(current_user.profile) %></li>
              </ul>
            </nav>
          </div>
          <br><br><br>

          <div id='content'>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <%= render 'layouts/footer' %>
    <!-- addons -->
    <%= render 'shared/freshchat' %>
  </body>
</html>